-- -- ========================================
-- -- ingredient
-- -- ========================================
-- INSERT INTO ingredient (ingredient_name, min_intake_value, max_intake_value, display_unit) VALUES
--                                                                                                ('비타민 C', 50, 2000, 'mg'),
--                                                                                                ('비타민 D', 10, 100, 'µg'),
--                                                                                                ('마그네슘', 100, 400, 'mg');
--
-- -- ========================================
-- -- product
-- -- ========================================
-- INSERT INTO product (PRDLST_NM, PRIMARY_FNCLTY, NTK_MTHD, IFTKN_ATNT_MATR_CN) VALUES
--                                                                                   ('비타민C 1000', '항산화, 면역력 증진', '1일 1회', '과다 섭취 주의'),
--                                                                                   ('비타민D 플러스', '뼈 건강', '1일 1회 식후', '지방과 함께 섭취'),
--                                                                                   ('마그네슘 밸런스', '근육 이완', '1일 2회', '설사 주의');
--
-- -- ========================================
-- -- product_ingredient
-- -- ========================================
-- INSERT INTO product_ingredient (product_id, ingredient_id, ingredient_amount, amount_unit) VALUES
--                                                                                                (1, 1, 1000, 'mg'),
--                                                                                                (2, 2, 25, 'µg'),
--                                                                                                (3, 3, 200, 'mg');
--
-- -- ========================================
-- -- user
-- -- ========================================
-- INSERT INTO `user` (email, password, name, role, oauth_provider, oauth_id, status, age_group, gender)
-- VALUES
--     ('user1@test.com', 'encoded_pw1', '홍길동', 'USER', NULL, NULL, 'ACTIVE', 'TWENTY', 'MALE'),
--     ('user2@test.com', 'encoded_pw2', '김영희', 'USER', NULL, NULL, 'ACTIVE', 'THIRTY', 'FEMALE'),
--     ('admin@test.com', 'encoded_pw3', '관리자', 'ADMIN', NULL, NULL, 'ACTIVE', 'FORTY', 'MALE');
--
-- -- ========================================
-- -- user_product
-- -- ========================================
-- INSERT INTO user_product (
--     user_id, product_id, nickname,
--     daily_dose, dose_amount, dose_unit, active
-- ) VALUES
--       (1, 1, '아침 비타민C', 1, 1000, 'mg', FALSE),
--       (1,  2, '비타민D', 1, 25, 'µg',  FALSE),
--       (2,  3, '마그네슘', 2, 200, 'mg',  FALSE);
--
-- -- ========================================
-- -- intake_record
-- -- ========================================
-- INSERT INTO intake_record (user_product_id, taken, intake_date) VALUES
--                                                                     (1, TRUE, '2025-01-10'),
--                                                                     (2, FALSE, '2025-01-10'),
--                                                                     (3, TRUE, '2025-01-10');
--
-- -- ========================================
-- -- notification
-- -- ========================================
-- INSERT INTO notification (
--     user_id, user_product_id, intake_time,
--     enabled, isTaken, category
-- ) VALUES
--       (1, 1, '08:00:00', TRUE, FALSE, 'INTAKE'),
--       (1, 2, '09:00:00', TRUE, FALSE, 'INTAKE'),
--       (2, 3, '20:00:00', TRUE, TRUE, 'INTAKE');
--
-- -- ========================================
-- -- notification_log
-- -- ========================================
-- INSERT INTO notification_log (
--     user_id, user_product_id, notification_type, sent_at
-- ) VALUES
--       (1, 1, 'PUSH', '2025-01-10 08:00:00'),
--       (1, 2, 'PUSH', '2025-01-10 09:00:00'),
--       (2, 3, 'PUSH', '2025-01-10 20:00:00');
--
-- -- ========================================
-- -- notification_setting (방해금지)
-- -- ========================================
-- INSERT INTO notification_setting (
--     user_id, quiet_start, quiet_end, enabled
-- ) VALUES
--       (1, '2025-01-10 22:00:00', '2025-01-11 07:00:00', TRUE),
--       (2, '2025-01-10 23:00:00', '2025-01-11 06:00:00', TRUE),
--       (3, '2025-01-10 00:00:00', '2025-01-10 23:59:59', FALSE);
--
-- -- ========================================
-- -- disease
-- -- ========================================
-- INSERT INTO disease (sick_name) VALUES
--                                     ('고혈압'),
--                                     ('당뇨'),
--                                     ('골다공증');
--
-- -- ========================================
-- -- user_disease
-- -- ========================================
-- INSERT INTO user_disease (user_id, disease_id) VALUES
--                                                    (1, 1),
--                                                    (2, 2),
--                                                    (1, 3);
--
-- -- ========================================
-- -- user_fcm_token
-- -- ========================================
-- INSERT INTO user_fcm_token (user_id, token, platform, active) VALUES
--                                                                   (1, 'fcm_token_user1_web', 'WEB', TRUE),
--                                                                   (1, 'fcm_token_user1_android', 'ANDROID', TRUE),
--                                                                   (2, 'fcm_token_user2_web', 'WEB', TRUE);
