services:
  app:
    build: .
    container_name: yaksok-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: docker
